#!/usr/bin/env python3
"""Render a metrics report JSON as a pull request comment.

Kept as a standalone script rather than a CLI feature: it consumes RAAG's own
--export-metrics output, which means it exercises that JSON format as a real
contract the same way the audit log's stored prompt does — if the export
format ever drifts, this script breaks loudly instead of a downstream
consumer silently misreading it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_STATUS_ICON = {True: "✅", False: "❌"}


def _severity_icon(severity: str) -> str:
    return "🔴" if severity == "error" else "🟡"


def format_comment(report: dict) -> str:
    summary = report["summary"]
    violations = report["violations"]
    thresholds = report["thresholds"]

    errors = [v for v in violations if v["severity"] == "error"]
    warnings = [v for v in violations if v["severity"] == "warning"]
    passed = len(errors) == 0

    lines: list[str] = []

    lines.append(f"## {_STATUS_ICON[passed]} RAAG Architectural Analysis")
    lines.append("")
    lines.append(
        f"**{summary['node_count']} files, {summary['edge_count']} dependencies, "
        f"{summary['cycle_count']} cycle(s).**"
    )
    lines.append("")

    if report.get("resolution"):
        lines.append(f"_{report['resolution']}_")
        lines.append("")

    if passed:
        lines.append(
            f"No error-severity violations. "
            f"({len(warnings)} warning(s) — not blocking.)"
        )
    else:
        lines.append(
            f"**{len(errors)} error(s)** push a core module's instability past "
            f"the configured threshold (`{thresholds['max_instability']}`), or "
            f"introduce a dependency cycle. This blocks the merge."
        )
        lines.append("")
        lines.append("| | Rule | Module | Detail |")
        lines.append("|---|---|---|---|")
        for violation in errors[:15]:
            lines.append(
                f"| {_severity_icon(violation['severity'])} "
                f"| `{violation['rule']}` "
                f"| `{violation['subject']}` "
                f"| {violation['message']} |"
            )
        if len(errors) > 15:
            lines.append(f"| | | | ... and {len(errors) - 15} more |")

    if warnings:
        lines.append("")
        lines.append(f"<details><summary>{len(warnings)} warning(s)</summary>")
        lines.append("")
        lines.append("| Rule | Module | Detail |")
        lines.append("|---|---|---|")
        for violation in warnings[:20]:
            lines.append(
                f"| `{violation['rule']}` | `{violation['subject']}` "
                f"| {violation['message']} |"
            )
        if len(warnings) > 20:
            lines.append(f"| | | ... and {len(warnings) - 20} more |")
        lines.append("")
        lines.append("</details>")

    lines.append("")
    lines.append(
        "<sub>Generated by "
        "[RAAG](https://github.com/amankarki151/RAAG) — "
        "instability gated on modules with meaningful afferent coupling; "
        "isolated leaves are not flagged for being correctly unstable.</sub>"
    )

    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: format_pr_comment.py <metrics.json>", file=sys.stderr)
        return 2

    report_path = Path(sys.argv[1])
    if not report_path.exists():
        print(f"error: {report_path} does not exist", file=sys.stderr)
        return 2

    report = json.loads(report_path.read_text(encoding="utf-8"))
    print(format_comment(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())